name: visual_editor
description: A rich text editor supporting mobile and web (Demo App @ visualspace.app)
version: 0.0.2
homepage: https://visualspace.app
repository: https://github.com/visual-space/visual-editor

environment:
  sdk: ">=3.1.5 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  flutter_keyboard_visibility: ^6.0.0
  image_picker: ^1.1.2
  photo_view: ^0.15.0
  quiver: ^3.2.1
  string_validator: ^1.1.0
  url_launcher: ^6.3.0
  video_player: ^2.9.1
  characters: ^1.3.0
  youtube_player_flutter: ^9.0.1
  diff_match_patch: ^0.4.1
  i18n_extension: ^12.0.1
  device_info_plus: ^10.1.0
  google_fonts: ^6.2.1
  flutter_colorpicker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: 1.11.1

# The following section is specific to Flutter.
flutter: null
